/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type TransactionHistoryOverridesProps = {
    TransactionHistory?: PrimitiveOverrideProps<ViewProps>;
    Card?: PrimitiveOverrideProps<ViewProps>;
    Showing?: PrimitiveOverrideProps<ViewProps>;
    "Showing 06 of 100"?: PrimitiveOverrideProps<TextProps>;
    Arrow36612989?: PrimitiveOverrideProps<ViewProps>;
    Vector36612990?: PrimitiveOverrideProps<IconProps>;
    Arrow36612991?: PrimitiveOverrideProps<ViewProps>;
    Vector36612992?: PrimitiveOverrideProps<IconProps>;
    Border?: PrimitiveOverrideProps<ViewProps>;
    "Vector 13"?: PrimitiveOverrideProps<IconProps>;
    "Vector 15"?: PrimitiveOverrideProps<IconProps>;
    "Vector 16"?: PrimitiveOverrideProps<IconProps>;
    "Vector 17"?: PrimitiveOverrideProps<IconProps>;
    "Vector 18"?: PrimitiveOverrideProps<IconProps>;
    "Vector 19"?: PrimitiveOverrideProps<IconProps>;
    "Vector 20"?: PrimitiveOverrideProps<IconProps>;
    "06"?: PrimitiveOverrideProps<ViewProps>;
    Australia36613002?: PrimitiveOverrideProps<TextProps>;
    $155?: PrimitiveOverrideProps<TextProps>;
    "02 March 202136613004"?: PrimitiveOverrideProps<TextProps>;
    "ABC-06"?: PrimitiveOverrideProps<TextProps>;
    Status36613006?: PrimitiveOverrideProps<FlexProps>;
    Unpaid36613007?: PrimitiveOverrideProps<TextProps>;
    Checkbox36613008?: PrimitiveOverrideProps<ViewProps>;
    "Dot Menu36613009"?: PrimitiveOverrideProps<ViewProps>;
    Vector36613010?: PrimitiveOverrideProps<IconProps>;
    Vector36613011?: PrimitiveOverrideProps<IconProps>;
    Vector36613012?: PrimitiveOverrideProps<IconProps>;
    "05"?: PrimitiveOverrideProps<ViewProps>;
    Australia36613014?: PrimitiveOverrideProps<TextProps>;
    $124?: PrimitiveOverrideProps<TextProps>;
    "02 March 202136613016"?: PrimitiveOverrideProps<TextProps>;
    "ABC-05"?: PrimitiveOverrideProps<TextProps>;
    Status36613018?: PrimitiveOverrideProps<FlexProps>;
    Expense?: PrimitiveOverrideProps<TextProps>;
    Checkbox36613020?: PrimitiveOverrideProps<ViewProps>;
    "Dot Menu36613021"?: PrimitiveOverrideProps<ViewProps>;
    Vector36613022?: PrimitiveOverrideProps<IconProps>;
    Vector36613023?: PrimitiveOverrideProps<IconProps>;
    Vector36613024?: PrimitiveOverrideProps<IconProps>;
    "04"?: PrimitiveOverrideProps<ViewProps>;
    Australia36613026?: PrimitiveOverrideProps<TextProps>;
    $140?: PrimitiveOverrideProps<TextProps>;
    "02 March 202136613028"?: PrimitiveOverrideProps<TextProps>;
    "ABC-04"?: PrimitiveOverrideProps<TextProps>;
    Status36613030?: PrimitiveOverrideProps<FlexProps>;
    Unpaid36613031?: PrimitiveOverrideProps<TextProps>;
    Checkbox36613032?: PrimitiveOverrideProps<ViewProps>;
    "Dot Menu36613033"?: PrimitiveOverrideProps<ViewProps>;
    Vector36613034?: PrimitiveOverrideProps<IconProps>;
    Vector36613035?: PrimitiveOverrideProps<IconProps>;
    Vector36613036?: PrimitiveOverrideProps<IconProps>;
    "03"?: PrimitiveOverrideProps<ViewProps>;
    Australia36613038?: PrimitiveOverrideProps<TextProps>;
    $49?: PrimitiveOverrideProps<TextProps>;
    "02 March 202136613040"?: PrimitiveOverrideProps<TextProps>;
    "ABC-03"?: PrimitiveOverrideProps<TextProps>;
    Status36613042?: PrimitiveOverrideProps<FlexProps>;
    Draf?: PrimitiveOverrideProps<TextProps>;
    Checkbox36613044?: PrimitiveOverrideProps<ViewProps>;
    "Dot Menu36613045"?: PrimitiveOverrideProps<ViewProps>;
    Vector36613046?: PrimitiveOverrideProps<IconProps>;
    Vector36613047?: PrimitiveOverrideProps<IconProps>;
    Vector36613048?: PrimitiveOverrideProps<IconProps>;
    "02"?: PrimitiveOverrideProps<ViewProps>;
    Australia36613050?: PrimitiveOverrideProps<TextProps>;
    $400?: PrimitiveOverrideProps<TextProps>;
    "02 March 202136613052"?: PrimitiveOverrideProps<TextProps>;
    "ABC-02"?: PrimitiveOverrideProps<TextProps>;
    Paid36613054?: PrimitiveOverrideProps<TextProps>;
    Checkbox36613055?: PrimitiveOverrideProps<ViewProps>;
    "Dot Menu36613056"?: PrimitiveOverrideProps<ViewProps>;
    Vector36613057?: PrimitiveOverrideProps<IconProps>;
    Vector36613058?: PrimitiveOverrideProps<IconProps>;
    Vector36613059?: PrimitiveOverrideProps<IconProps>;
    Status36613060?: PrimitiveOverrideProps<FlexProps>;
    "01"?: PrimitiveOverrideProps<ViewProps>;
    Indonesia?: PrimitiveOverrideProps<TextProps>;
    $300?: PrimitiveOverrideProps<TextProps>;
    "02 March 202136613064"?: PrimitiveOverrideProps<TextProps>;
    "ABC-01"?: PrimitiveOverrideProps<TextProps>;
    Status36613066?: PrimitiveOverrideProps<FlexProps>;
    Paid36613067?: PrimitiveOverrideProps<TextProps>;
    Checkbox36613068?: PrimitiveOverrideProps<ViewProps>;
    "Dot Menu36613069"?: PrimitiveOverrideProps<ViewProps>;
    Vector36613070?: PrimitiveOverrideProps<IconProps>;
    Vector36613071?: PrimitiveOverrideProps<IconProps>;
    Vector36613072?: PrimitiveOverrideProps<IconProps>;
    "check 2"?: PrimitiveOverrideProps<ViewProps>;
    Group36613074?: PrimitiveOverrideProps<ViewProps>;
    Group36613075?: PrimitiveOverrideProps<ViewProps>;
    Vector36613076?: PrimitiveOverrideProps<IconProps>;
    Header?: PrimitiveOverrideProps<ViewProps>;
    ID?: PrimitiveOverrideProps<TextProps>;
    Date?: PrimitiveOverrideProps<TextProps>;
    Location?: PrimitiveOverrideProps<TextProps>;
    Amount?: PrimitiveOverrideProps<TextProps>;
    Status36613082?: PrimitiveOverrideProps<TextProps>;
    Checkbox36613083?: PrimitiveOverrideProps<ViewProps>;
} & EscapeHatchProps;
export declare type TransactionHistoryProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: TransactionHistoryOverridesProps | undefined | null;
}>;
export default function TransactionHistory(props: TransactionHistoryProps): React.ReactElement;
